distance: null
basis: 'sto-3g'
nelecas: 10
norbcas: 9
spin: 0
charge: 0
geometry: [
    ['C', [0.000010, -0.000000, 0.000008]],
    ['H', [-0.000028, -0.000000, 1.096847]],
    ['H', [1.034133, -0.000000, -0.365570]],
    ['H', [-0.517034, 0.895565, -0.365623]],
    ['H', [-0.517034, -0.895565, -0.365623]],
]