distance: null
basis: 'sto-3g'
nelecas: 30
norbcas: 20
spin: 0
charge: 0
geometry: [
    ['Fe', [0.096357, 0.000553, 0.000000]],
    ['Fe', [2.376157, 0.000041, -0.000000]],
    ['S', [0.937458, 1.736164, 0.000001]],
    ['S', [0.937392, -1.735176, -0.000001]],
]