distance: 1.1
basis: 'sto-3g'
nelecas: 4
norbcas: 4
spin: 0
charge: 0
geometry:
  - - H
    - - 0.0
      - 0.0
      - 0.0
  - - H
    - - 0.0
      - 0.0
      - ${molecule.distance}
  - - H
    - - 0.0
      - 0.0
      - ${mul:${molecule.distance}, 2}
  - - H
    - - 0.0
      - 0.0
      - ${mul:${molecule.distance}, 3}
