title: "Naphthalene"
distance: null
geometry: [
    ['C', [2.439610, 0.709984, -0.000000]],
    ['C', [1.247664, 1.406267, -0.000000]],
    ['C', [0.000120, 0.719074, -0.000000]],
    ['C', [-0.000099, -0.719006, -0.000000]],
    ['C', [1.247483, -1.406136, -0.000000]],
    ['C', [2.439497, -0.709959, -0.000000]],
    ['H', [-1.245599, 2.492934, -0.000000]],
    ['H', [3.383860, 1.245234, -0.000000]],
    ['H', [1.244964, 2.492771, -0.000000]],
    ['C', [-1.247340, 1.406413, -0.000000]],
    ['C', [-1.247664, -1.406218, -0.000000]],
    ['H', [1.244751, -2.492637, -0.000000]],
    ['H', [3.383684, -1.245321, -0.000000]],
    ['C', [-2.439746, -0.710189, -0.000000]],
    ['C', [-2.439035, 0.709762, -0.000000]],
    ['H', [-1.244874, -2.492723, 0.000000]],
    ['H', [-3.384046, -1.245366, -0.000000]],
    ['H', [-3.383203, 1.245123, -0.000000]],
]
basis: 'sto-3g'
nelecas: 10
norbcas: 10
spin: 0
charge: 0